name: utrgan
channels:
  - bioconda
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=2.2.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.11.16
  - aiosignal=1.3.2
  - anyio=4.9.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - astunparse=1.6.3
  - async-lru=2.0.5
  - async-timeout=5.0.1
  - attrs=25.3.0
  - babel=2.17.0
  - beautifulsoup4=4.13.3
  - biopython=1.85
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - blinker=1.9.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.1.31
  - cached_property=1.5.2
  - cachetools=5.5.2
  - certifi=2025.1.31
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - click=8.1.8
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.3.0
  - cpython=3.9.22
  - cryptography=39.0.0
  - cuda-version=11.8
  - cudatoolkit=11.8.0
  - cudnn=8.9.7.29
  - cycler=0.12.1
  - debugpy=1.8.14
  - decorator=5.2.1
  - defusedxml=0.7.1
  - einops=0.8.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - filelock=3.18.0
  - flatbuffers=22.12.06
  - fonttools=4.57.0
  - fqdn=1.5.1
  - freetype=2.13.3
  - frozenlist=1.5.0
  - gast=0.4.0
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.1.5
  - google-auth=2.39.0
  - google-auth-oauthlib=0.4.6
  - google-pasta=0.2.0
  - grpcio=1.51.1
  - gsl=2.7
  - h11=0.14.0
  - h2=4.2.0
  - h5py=3.9.0
  - hdf5=1.14.0
  - hpack=4.1.0
  - httpcore=1.0.7
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=70.1
  - idna=3.10
  - importlib-metadata=8.6.1
  - importlib-resources=6.5.2
  - importlib_resources=6.5.2
  - ipykernel=6.29.5
  - ipython=8.18.1
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.4.2
  - jpeg=9e
  - json5=0.12.0
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.12.0
  - jupyter_server=2.15.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.0
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - keras=2.11.0
  - keras-preprocessing=1.1.2
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.20.1
  - lcms2=2.15
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libabseil=20220623.0
  - libaec=1.1.3
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcurl=7.87.0
  - libdeflate=1.17
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.0
  - libffi=3.4.6
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libgomp=14.2.0
  - libgrpc=1.51.1
  - libhwloc=2.9.1
  - libiconv=1.18
  - libjpeg-turbo=2.1.4
  - liblapack=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libmagma=2.7.1
  - libmagma_sparse=2.7.1
  - libnghttp2=1.51.0
  - libnsl=2.0.1
  - libopenblas=0.3.29
  - libpng=1.6.47
  - libprotobuf=3.21.12
  - libsodium=1.0.18
  - libsqlite=3.49.1
  - libssh2=1.10.0
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libtiff=4.5.0
  - libuuid=2.38.1
  - libwebp-base=1.5.0
  - libxcb=1.13
  - libxcrypt=4.4.36
  - libxml2=2.10.3
  - libzlib=1.3.1
  - llvm-openmp=20.1.2
  - magma=2.7.1
  - markdown=3.6
  - markupsafe=3.0.2
  - matplotlib-base=3.9.4
  - matplotlib-inline=0.1.7
  - mistune=3.1.3
  - mkl=2022.2.1
  - ml_dtypes=0.2.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.3.2
  - munkres=1.1.4
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - nccl=2.26.2.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.2.1
  - notebook=7.4.0
  - notebook-shim=0.2.4
  - numpy=1.26.4
  - oauthlib=3.2.2
  - openjpeg=2.5.0
  - openssl=1.1.1w
  - opt_einsum=3.4.0
  - overrides=7.7.0
  - packaging=24.2
  - pandas=2.2.3
  - pandocfilters=1.5.0
  - parso=0.8.4
  - patsy=1.0.1
  - perl=5.32.1
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=25.0.1=pyh8b19718_0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.7
  - polyleven=0.9.0
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.50
  - propcache=0.3.1
  - protobuf=4.21.12
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.2
  - pycparser=2.22
  - pygments=2.19.1
  - pyjwt=2.10.1
  - pyopenssl=23.2.0
  - pyparsing=3.2.3
  - pysocks=1.7.1
  - python=3.9.15
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.1
  - python-flatbuffers=25.2.10
  - python-json-logger=2.0.7
  - python-tzdata=2025.2
  - python_abi=3.9
  - pytorch=2.0.0
  - pytz=2025.2
  - pyu2f=0.1.5
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qhull=2020.2
  - re2=2022.06.01
  - readline=8.2
  - referencing=0.36.2
  - requests=2.32.3
  - requests-oauthlib=2.0.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.24.0
  - rsa=4.9
  - scikit-learn=1.6.1
  - scipy=1.13.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.3
  - setuptools=78.1.0
  - six=1.17.0
  - sleef=3.8
  - snappy=1.1.10
  - sniffio=1.3.1
  - soupsieve=2.5
  - stack_data=0.6.3
  - statsmodels=0.14.4
  - sympy=1.13.3
  - tbb=2021.9.0
  - tensorboard=2.11.2
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.11.0
  - tensorflow-base=2.11.0
  - tensorflow-estimator=2.11.0
  - tensorflow-gpu=2.11.0
  - termcolor=3.0.1
  - terminado=0.18.1
  - threadpoolctl=3.6.0
  - tinycss2=1.4.0
  - tk=8.6.13
  - tomli=2.2.1
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20241206
  - typing-extensions=4.13.2
  - typing_extensions=4.13.2
  - typing_utils=0.1.0
  - tzdata=2025b
  - unicodedata2=16.0.0
  - uri-template=1.3.0
  - viennarna=2.7.0
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - werkzeug=3.1.3
  - wheel=0.45.1
  - wrapt=1.14.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - yarl=1.18.3
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - urllib3==1.26.20
